spec: add the systemd build requires
This will fix the following error:
error: File must begin with "/": %{_unitdir}/

Signed-off-by: Xiubo Li <xiubli@redhat.com>